Repository SKNETWORKS-FAMILY-AICAMP/SKN09-FINAL-4Team, pull requests merged in 2025-06, with the labels that each got.

#16 Feature/password
  web/static/css/chat_header.css
  web/static/css/common.css
  web/static/css/petmind-join.css
  web/static/css/petmind-search.css
  web/templates/email_temp_password.html
  web/templates/user/home_01.html
  web/templates/user/join_p_terms_privacy.html
  web/templates/user/join_p_terms_service.html
  web/templates/user/search_01.html
  web/templates/user/search_02.html
  web/user/urls.py
  web/user/views.py
Labels: fix, feat

#17 Refeator: 반려견 정보 수정, 삭제 기능 추가
  web/chat/views.py
  web/dogs/urls.py
  web/dogs/views.py
  web/static/css/petmind-join.css
  web/static/css/right_sidebar.css
  web/templates/common/right_sidebar.html
  web/templates/dogs/dog_info_join.html
Labels: refactor, feat

#19 fix: image upload logic refactor
  web/templates/dogs/dog_info_join.html
Labels: fix

#20 refector: code refector
  web/.gitignore
  web/dogs/views.py
  web/static/css/chat.css
  web/static/css/chat_header.css
  web/static/css/chat_talk.css
  web/static/css/common.css
  web/static/css/petmind-chat.css
  web/static/js/chat_member_sidebar.js
  web/templates/chat/chat.html
  web/templates/chat/chat_talk.html
  web/templates/common/feedback_modal.html
  web/templates/common/sidebar.html
  web/templates/common/update_modal.html
  web/user/admin.py
  web/user/tests.py
  web/user/utils.py
Labels: refactor

#28 feat: chat report
  web/chat/admin.py
  web/chat/report_utils/gpt_report.py
  web/chat/report_utils/report_pdf.py
  web/chat/urls.py
  web/chat/views.py
  web/petmind/settings.py
  web/petmind/urls.py
  web/static/css/chat_header.css
  web/static/css/chat_report_feedback.css
  web/static/css/report_template.css
  web/static/images/download_icon.png
  web/static/images/sample_dog.png
  web/static/images/star_g.png
  web/static/images/star_y.png
  web/static/js/chat_report_feedback.js
  web/templates/chat/chat_report_feedback.html
  web/templates/chat/chat_talk.html
  web/templates/chat/report_template.html
  web/templates/common/chat_header.html
Labels: web ui, feat

#33 feat: petmind_version_02
  .github/ISSUE_TEMPLATE/issue_template.md
  ai-engine/model_code/main.py
  ai-engine/model_code/qwen3_chat_response.ipynb
  ai-engine/model_code/qwen3_model_utils.py
  web/.gitignore
  web/chat/admin.py
  web/chat/report_utils/gpt_report.py
  web/chat/report_utils/report_pdf.py
  web/chat/urls.py
  web/chat/utils.py
  web/chat/views.py
  web/petmind/settings.py
  web/petmind/urls.py
  web/static/css/chat.css
  web/static/css/chat_header.css
  web/static/css/chat_report_feedback.css
  web/static/css/chat_talk.css
  web/static/css/common.css
  web/static/css/feedback_modal.css
  web/static/css/petmind-info.css
  web/static/css/petmind-join.css
  web/static/css/petmind-login.css
  web/static/css/petmind-search.css
  web/static/css/report_template.css
  web/static/css/update_modal.css
  web/static/images/download_icon.png
  web/static/images/sample_dog.png
  web/static/images/star_g.png
  web/static/images/star_y.png
  web/static/js/chat_member_sidebar.js
  web/static/js/chat_report_feedback.js
  web/static/js/recommend.js
  web/static/js/right_sidebar.js
  web/templates/chat/chat.html
  web/templates/chat/chat_report_feedback.html
  web/templates/chat/chat_talk.html
  web/templates/chat/report_template.html
  web/templates/common/chat_header.html
  web/templates/common/feedback_modal.html
  web/templates/common/right_sidebar.html
  web/templates/common/update_modal.html
  web/templates/dogs/dog_info_join.html
  web/templates/user/home_01.html
  web/templates/user/join_01.html
  web/templates/user/search_01.html
  web/user/admin.py
  web/user/tests.py
  web/user/utils.py
Labels: refactor, fix, feat

#34 fix: modal conflict
  web/static/css/chat_report_feedback.css
  web/static/js/chat_report_feedback.js
  web/templates/chat/chat_report_feedback.html
Labels: bug, fix, web ui

#35 fix: modal delay
  web/static/js/chat_report_feedback.js
Labels: bug, fix, web ui

#36 Feat: 채팅 secure 적용
  web/chat/views.py
  web/templates/403.html
Labels: feat

#42 Feat: enhance mobile UI
  web/static/css/chat_report_feedback.css
  web/static/js/chat_report_feedback.js
  web/templates/chat/chat_report_feedback.html
Labels: feat

#49 Fix/sidebar-layout-overlap
  web/static/css/chat_talk.css
  web/static/css/sidebar.css
  web/templates/chat/chat.html
Labels: bug

#51 fix: setting-button
  web/templates/common/sidebar.html
Labels: bug

#53 Fix: sidebar
  web/chat/views.py
  web/static/js/chat_member_sidebar.js
  web/templates/common/sidebar.html
Labels: bug

#55 fix: 새 채팅 시작 로직 수정
  web/chat/views.py
  web/templates/chat/chat.html
  web/templates/common/sidebar.html
Labels: bug

#58 fix: chat duplication
  web/chat/views.py
  web/static/js/chat_talk.js
Labels: bug

#63 fix: chat path modified
  web/static/js/chat_member_sidebar.js
Labels: bug, fix

#65 fix: 사용자 및 모델 메시지에 실시간 타임스탬프 표시 기능 개선
  web/static/css/chat_talk.css
  web/static/js/chat_talk.js
Labels: bug

#66 feat: petmind_version_05
  web/chat/templatetags/custom_markdown.py
  web/static/css/chat_header.css
  web/static/css/chat_report_feedback.css
  web/static/css/chat_talk.css
  web/static/js/chat_member_sidebar.js
  web/static/js/chat_talk.js
  web/templates/403.html
Labels: bug, web ui

#69 fix: chat report image
  ai-engine/model_code/qwen3_chat_response.ipynb
  web/chat/report_utils/report_pdf.py
  web/chat/views.py
Labels: bug, fix

#70 fix: Hide image upload button and display a fixed health notice message at the bottom of the chat screen.
  web/static/css/chat.css
  web/templates/chat/chat.html
  web/templates/chat/chat_talk.html
Labels: bug, fix

#76 fix: sidebar chat title
  web/static/css/sidebar.css
  web/static/js/chat_member_sidebar.js
  web/templates/common/sidebar.html
Labels: bug

#83 Feat: 스트리밍 채팅 기능 추가
  web/chat/utils.py
  web/chat/views.py
  web/static/css/chat_talk.css
  web/static/js/chat_talk.js
  web/templates/chat/chat_talk.html
Labels: feat

#85 feat: petmind_version_1
  web/chat/utils.py
  web/chat/views.py
  web/static/css/chat_talk.css
  web/static/js/chat_talk.js
  web/static/js/recommend.js
  web/templates/chat/chat.html
  web/templates/chat/chat_talk.html
  web/templates/common/update_modal.html
  web/templates/user/join_01.html
  web/templates/user/join_p_terms_privacy.html
  web/templates/user/join_p_terms_service.html
Labels: bug, fix, feat

#88 fix: wrong input alret
  web/templates/dogs/dog_info_join.html
Labels: bug, fix

#91 refactor: chat ui
  web/chat/templatetags/custom_markdown.py
Labels: refactor

#92 refactor: petmind_version_1
  web/chat/templatetags/custom_markdown.py
  web/static/js/chat_talk.js
  web/templates/dogs/dog_info_join.html
Labels: feat

#94 Fix: chat message stream
  web/chat/templatetags/custom_markdown.py
  web/chat/views.py
  web/static/css/chat_talk.css
  web/static/js/chat_talk.js
  web/templates/chat/chat_talk.html
Labels: fix, web ui

#95 fix: petmind_version_1
  web/chat/templatetags/custom_markdown.py
  web/chat/views.py
  web/static/css/chat_talk.css
  web/static/js/chat_talk.js
  web/templates/chat/chat_talk.html
Labels: fix

#96 fix:model logic - max tokens & context
  ai-engine/model_code/main.py
  ai-engine/model_code/qwen3_model_utils.py
Labels: enhancement, fix

#98 Feat: 반려견 성격 유형 검사 테스트 기능 추가
  web/chat/views.py
  web/dogs/models.py
  web/dogs/urls.py
  web/dogs/utils.py
  web/dogs/views.py
  web/static/css/chat.css
  web/static/css/dog_personality_result.css
  web/static/css/dog_personality_test.css
  web/static/css/right_sidebar.css
  web/templates/chat/chat.html
  web/templates/common/chat_header.html
  web/templates/common/right_sidebar.html
  web/templates/dogs/dog_personality_result.html
  web/templates/dogs/dog_personality_test.html
Labels: feat

#97 fix:로고 클릭 페이지 수정,콘텐츠 수정, 채팅 이미지 표시 수정
  web/chat/views.py
  web/templates/chat/chat_talk.html
  web/templates/common/chat_header.html
Labels: bug

#99 fix: link
  web/templates/common/chat_header.html
Labels: bug

#101 fix: breed_name
  web/chat/views.py
Labels: fix

#102 Refactor: chat image 메인 창에서는 업로드 취소
  web/static/css/chat.css
  web/templates/chat/chat.html
Labels: fix

#108 Feat/chat prompt
  ai-engine/model_code/main.py
  ai-engine/model_code/qwen3_model_utils.py
  web/chat/utils.py
  web/chat/views.py
Labels: enhancement, feat

#111 fix: petmind_version_final
  web/chat/views.py
Labels: bug

#115 fix: report date
  web/chat/views.py
Labels: bug

#116 Fix : petmind_version_final
  web/chat/views.py
Labels: bug

#117 fix: report_image_error
  web/chat/views.py
Labels: fix

#118 fix: final_petmind
  web/chat/views.py
Labels: fix

#120 refactor: chat ui
  web/static/css/chat_talk.css
  web/static/js/chat_talk.js
  web/templates/chat/chat_talk.html
Labels: refactor

#123 update Readme
  README.md
Labels: documentation
